### ISSUE TITLE
Handle EOF and ^C interrupt

### ISSUE THREAD

**Issue by Technohacker** [dvtate/rpn#3]
Pressing Ctrl + D in Linux (or Ctrl + Z in Windows) prints an error, rather than stopping the interpreter, unlike other interpreters like sh, python, node, perl, etc.

Ctrl + C stops yoda, instead of getting ignored.

**Comment by dvtate** [comment]
I'll fix this soon, I currently have atexit() being handled by a function in my terminal colors library and I'll need to change it.

**Comment by dvtate** [comment]
I have it there since if I didn't and the user changed the text color it would stay that color after the program finished.

**Comment by Technohacker** [comment]
Aah kay, good to know :)

**Comment by dvtate** [comment]
Ctrl + C and Ctrl + D are both handled now, however given the current language structure, implementing Ctrl+L would be difficult and hinder performance (although in the shell it wouldn't matter). 
Either way, thanks for pointing this out!
